apiVersion: falarica.io/v1alpha1
kind: Presto
metadata:
  name: mycluster
spec:
  service:
    type: "NodePort"
    port: 8100
    nodePort: 30002
  catalogs:
    catalogSpec:
      - name: newtpch
        content:
          connector.name: tpch
      - name: newtpcds
        content:
          connector.name: tpcds
# kubectl create secret generic tpchsecret --from-literal=mytpch='connector.name=tpch' --from-literal=myjmx='connector.name=jmx'
#    catalogSecrets:
#      - secretName: tpchsecret
#        secretKey: mytpch
#      - secretName: tpchsecret
#        secretKey: myjmx
  volumes:
  - name: spillvol
    emptyDir: {}
    mountPath: /prestospill
  coordinator:
    memoryLimit: "1Gi"
    cpuLimit: "0.5"
    # kubectl create secret  generic  prestokeystore  --from-file=/tmp/etc/prestoserverkeystore.jks
    httpsEnabled: false
    httpsKeyPairSecretName: "prestokeystore"
    httpsKeyPairSecretKey: "prestoserverkeystore.jks"
    httpsKeyPairPassword: "hemant"
  worker:
    memoryLimit: "1Gi"
    cpuLimit: "0.5"
    count: 1
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 20
    additionalProps:
      shutdown.grace-period: 10s
      spill-enabled: "true"
      spiller-spill-path: "/prestospill"
  additionalPrestoPropFiles:
    access-control.properties:
      access-control.name=read-only
