steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/steerd-presto-operator', '-f', 'docker/Dockerfile', '.']
images:
  - 'gcr.io/$PROJECT_ID/steerd-presto-operator'